"""Reviewed the failures

Revision ID: 86d35b6950ec
Revises: 5014d4890c53
Create Date: 2023-12-15 00:59:32.251776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d35b6950ec'
down_revision: Union[str, None] = '5014d4890c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('artist', sa.VARCHAR(), nullable=True))
    op.add_column('songs', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'duration')
    op.drop_column('songs', 'artist')
    # ### end Alembic commands ###
